run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gosimple      # Упрощение кода
    - govet         # Стандартный анализатор Go
    - ineffassign   # Бесполезные присваивания
    - staticcheck   # Статический анализ
    - unused        # Неиспользуемый код
    - gofmt         # Форматирование
    - misspell      # Опечатки
    - gocyclo       # Сложность функций
    - gosec         # Безопасность
  
  disable:
    - errcheck

linters-settings:
  gocyclo:
    min-complexity: 25
  
  gosec:
    excludes:
      - G404  # math/rand допустим
      - G201  # fmt.Sprintf для SQL допустим
      - G114  # http.ListenAndServe без таймаутов

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocyclo
  
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
